### PR TITLE
Added isVisible api on toast object

### PR DESCRIPTION
**Pull request by rahulnpadalkar**
`isVisible(id: String) => Boolean`

If the toast is visible it returns true and false.

#17 
 - [X] check if toast is active by id

### CODE REVIEW

**Comment by ankurk91** [comment]
Lodash is overkill to implement this feature

**Comment by rahulnpadalkar** [comment]
Yeah, what do you think about [this](https://www.npmjs.com/package/uuid)?

**Comment by rahulnpadalkar** [comment]
@ankurk91 removed lodash dependency as you rightly mentioned that it would be a overkill. Implemented a function instead.

**Comment by ankurk91** [comment]
Well, this is now how i have envisioned this feature to look like.
I will take a look on this feature after making the package compatible for Vue 3.0

**Pull request closed without merging**
