### PR TITLE
Added ability to keep a toast open

### PR DESCRIPTION
**Pull request by alessandromarotta**
Introduction of `"duration: 0;"` option to keep a toast open

### CODE REVIEW

**Comment by ankurk91** [comment]
Thanks for the PR.

I was thinking of having a separate prop something like `autoDismiss`,

```
autoDismiss : false
```
Will cause the toast NOT to initialise the timers.

**Comment by alessandromarotta** [comment]
There is only a "dismissible" property but it doesn't prevent to initialise the timers.
I think that "duration: 0;" could be a good way to get it.

**Comment by ankurk91** [comment]
>>`dismissible` prop
Agree naming is hard.

I am looking into other similar libraries on Github.

**Comment by alessandromarotta** [comment]
[vue-toasted](https://github.com/shakee93/vue-toasted) uses "duration: 0;"

**Comment by ankurk91** [comment]
closed by #46

**Pull request closed without merging**
