### PR TITLE
WIP: Implement additional thems

### PR DESCRIPTION
**Pull request by dimitor115**
So I've added an option to configure available theme.
I will add one more theme for sure, that is why there is WIP prefix :smile_cat: 
Due to #5

### CODE REVIEW

**Comment by dimitor115** [comment]
Ok I see and will need  to add: https://webpack.js.org/loaders/svg-inline-loader/

**Comment by ankurk91** [comment]
Rather than bundling all themes into one, i would like them to be separate file for each of the theme.
Bundle svg with theme-name.css rather than js.
Keep package size small.

**Comment by dimitor115** [comment]
@ankurk91 
> Bundle svg with theme-name.css rather than js.

Not sure if I understand it correctly. Do you mean sth like this?
```
icon-success {
  background-image: url('path/file.svg')
}
```

**Comment by dimitor115** [comment]
@ankurk91 How about this solution?

**Comment by dimitor115** [comment]
@ankurk91 I have some troubles on implementing another theme, and I would like to implement it in another PR. So that's my final version for this moment. Please take a look :smile:

**Comment by dimitor115** [comment]
@ankurk91 what about?

**Comment by ankurk91** [comment]
Hey, Sorry i am not getting time to look into it.

Building a Chrome extension now a days for a client :) 

In order to generate separate css files for each of the theme, we need to tweak webpack configs.

I will try my best to look into this asap.

Thanks for your patience.

**Comment by dimitor115** [comment]
> Hey, Sorry i am not getting time to look into it.
> 
> Building a Chrome extension now a days for a client :)
> 
> In order to generate separate css files for each of the theme, we need to tweak webpack configs.
> 
> I will try my best to look into this asap.
> 
> Thanks for your patience.

@ankurk91 up :smile:

**Comment by ankurk91** [comment]
@dimitor115 
I have made some progress on `next` branch
https://github.com/ankurk91/vue-toast-notification/tree/next

**Comment by ankurk91** [comment]
@dimitor115 
Please check version `0.1.0` and let me know if you like the implementation.

**Comment by dimitor115** [comment]
@ankurk91 So just just applied my them instead of presenting the multiple theme options ;) However it’s nice I like the new design 🥰

**Pull request closed without merging**
