### PR TITLE
Standardizes css class nomenclatures/ use BEM

### PR DESCRIPTION
**Pull request by jprodrigues70**
As commented by @LanFeusT23... it is important to standardize the prefix of the `vue-toast-notification` classes so that it is easier to apply a regex or similar rules

I used `v-toast` as prefix

https://github.com/ankurk91/vue-toast-notification/issues/31

### CODE REVIEW

**Comment by jprodrigues70** [comment]
@ankurk91 i'm sorry, i didn't see that someone openned a pull request with the the same idea, so if you want, reject my request, because i did after... 

But i need to say that my PR don't have the problems that the other have

**Comment by LanFeusT23** [comment]
I like this PR better because it uses `v-toast` rather than just `vt`, but technically the element `v-toast__container` shouldn't be the block for `v-toast`.
Ideally the `v-toast` should be what `v-notices` was, and `v-toast` would become `v-toast__item` or something alike.

**Comment by jprodrigues70** [comment]
@LanFeusT23 you're right. Would you see if it's correct now?

**Comment by LanFeusT23** [comment]
To me it looks good ^^

**Pull request merged**
